### ISSUE TITLE
Reduce bundle size

### ISSUE THREAD

**Issue by tomusher** [tomusher/wagtail-ai#1]
The JS bundle is quite large at the moment, mostly because it includes all of Draftail. Can we reuse Draftail from the Wagtail bundle without issues?

**Comment by timonweb** [comment]
First of all, thanks for starting it! I've been playing with Chat GPT and building my own interface with web components, but I wanted to start something similar for Wagtail, and here you are!

And yes, you can reuse Draftail from Wagtail instead. It's exposed as the `window.Draftail` global.

@tomdyson In my opinion, integration with ChatGPT should be a part of Wagtail. It's currently such a marketing booster and a very useful tool, of course.

**Comment by tomusher** [comment]
Thanks @timonweb! We're now reusing `window.Draftail` in 1.1.0.
