### ISSUE TITLE
Split the vector index to separate package

### ISSUE THREAD

**Issue by zerolab** [tomusher/wagtail-ai#13]
as the UI side of things and the vector index functionality are fairly well contained

**Comment by tomusher** [comment]
This makes sense - I've been struggling to finalise the API for the vector index stuff which means it's been harder to work on the existing features.

I'll break that stuff out in to a new package so I can work on that independently. Thanks for the support as always @zerolab!

**Comment by zerolab** [comment]
Happy to help with the new package (packaging, docs, GHA etc)

While at it, we'll need `from __future__ import annotations` or set a newer Python minimum. Will open an issue in the new repo when ready. tl;dr running with Python 3.8:
```
  File "/my_app/models.py", line 10, in <module>
    from wagtail_ai.index import VectorIndexed, EmbeddingField
  File "/venv/lib/python3.8/site-packages/wagtail_ai/index.py", line 302, in <module>
    def get_vector_indexes() -> dict[str, VectorIndex]:
TypeError: 'type' object is not subscriptable
```

**Comment by tomusher** [comment]
This is now split out in to https://github.com/tomusher/wagtail-vector-index - still plenty to tidy up (that annotation issue included).

Thanks for the suggestion.
