### ISSUE TITLE
Allow Wagtail developers to add new prompts

### ISSUE THREAD

**Issue by tomdyson** [tomusher/wagtail-ai#7]
e.g.

```python
WAGTAIL_AI_PROMPTS = wagtail_ai.DEFAULT_PROMPTS + [
    {
        "label": "Translate to French",
        "prompt": "translate the following text to French",
    },
    {
        "label": "Simplify",
        "prompt": "rewrite the following text to make it simpler and more succinct",
    },
]
```

**Comment by tomusher** [comment]
Absolutely, I've started working on this on the [feature/support-custom-prompts](https://github.com/tomusher/wagtail-ai/tree/feature/support-custom-prompts) branch.

**Comment by tomdyson** [comment]
Very nice! I hadn't thought about the `method: 'append' / 'replace'` consideration.

**Comment by tomusher** [comment]
This is done in 1.1.0. Thanks for the suggestion @tomdyson!
